version: "3"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: ""
      OPENAI_API_BASE: "https://blue-dev-openai.openai.azure.com/"
      OPENAI_API_VERSION: "2024-12-01-preview"
      OPENAI_DEPLOYMENT: "paper2ppt-gpt-4o"
